In [1]:
import numpy as np #importing numpy

In [3]:
array_1 = np.array([1,2,3,4,5])

In [4]:
array_2 = np.array([[1,2,3],[4,5,6]])

In [5]:
print(f"1D array : {array_1}")

1D array : [1 2 3 4 5]


In [7]:
print(f"2D array : \n {array_2}")

2D array : 
 [[1 2 3]
 [4 5 6]]


In [6]:
#creating numpy array from scratch

In [7]:
np.zeros((3,2)) #create array with all zeroes

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,4)) #creating array with all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full((3,3),6) #creating array with all "6"

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [10]:
np.eye(4) #creating 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.arange(1,12,5) 

array([ 1,  6, 11])

In [12]:
np.linspace(10,11,3)

array([10. , 10.5, 11. ])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(f"shape of array : {arr.shape}")
print(f"size of array : {arr.size}")
print(f"dimensions of array : {arr.ndim}")
print(f"data type of array : {arr.dtype}")

shape of array : (3, 3)
size of array : 9
dimensions of array : 2
data type of array : int64


In [20]:
#changing datatypes

In [30]:
arr = np.array([1,2,3,4] , dtype=np.float32)
arr.dtype

dtype('float32')

In [31]:
arr.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

In [32]:
#shaping and flattening array

In [35]:
arr = np.array([[1,2,3],[4,5,6]])

In [36]:
arr.shape

(2, 3)

In [38]:
reshaped = arr.reshape(3,2)

In [39]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
reshaped.flatten()

array([1, 2, 3, 4, 5, 6])