In [5]:
import numpy as np

In [12]:
stock_prices = "1420, 1385, 1402, 1450, 1398, 1411, 1467" #closing stock prices task 1

In [6]:
new_stock_price_list = list(map(lambda x:int(x),stock_prices.split(",")))
new_stock_price_list

[1420, 1385, 1402, 1450, 1398, 1411, 1467]

In [7]:
#creating numpy array from these prices
stock_prices_array = np.array(new_stock_price_list)
stock_prices_array

array([1420, 1385, 1402, 1450, 1398, 1411, 1467])

In [8]:
#properties of this array

In [10]:
print(f"shape of array : {stock_prices_array.shape} ")
print(f"size of array : {stock_prices_array.size}")
print(f"dimensions of array : {stock_prices_array.ndim}")
print(f"data type of array : {stock_prices_array.dtype}")

shape of array : (7,) 
size of array : 7
dimensions of array : 1
data type of array : int64


In [11]:
#changing the datatype
stock_prices_array.astype(np.float32)

array([1420., 1385., 1402., 1450., 1398., 1411., 1467.], dtype=float32)

In [13]:
#task 2 sensors temperatures

In [18]:
initial_temperature = np.zeros((4,5)) #initial sensors readings
initial_temperature

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
sensors_readings = np.ones((4,5))
sensors_readings

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
sensors_readings = np.full((4,5),-999)
sensors_readings

array([[-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999]])

In [23]:
sensors_readings = np.eye(4,5)
sensors_readings

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
#students marks task3

In [27]:
marks = np.array([85, 90, 78, 92, 70, 88, 95, 60, 82, 75, 91, 68])
marks

array([85, 90, 78, 92, 70, 88, 95, 60, 82, 75, 91, 68])

In [29]:
#properties
print(f"shape of array : {marks.shape}")
print(f"size of array : {marks.size}")
print(f"dimensions of array : {marks.ndim}")
print(f"data type of array : {marks.dtype}")

shape of array : (12,)
size of array : 12
dimensions of array : 1
data type of array : int64


In [31]:
reshaped = marks.reshape(3,4) #reshaping the array into 3x4
reshaped

array([[85, 90, 78, 92],
       [70, 88, 95, 60],
       [82, 75, 91, 68]])

In [33]:
flattening = reshaped.flatten()
flattening 
print(f"checking the size of reshaped array again : {flattening.size}")

checking the size of reshaped array again : 12


In [34]:
#task 4 timeline generator

In [43]:
video_frames = np.arange(0,100,5)
print(video_frames)
print()
#properties
print(f"shape of array : {video_frames.shape}")
print(f"size of the array : {video_frames.size}")
print(f"data type of the array : {video_frames.dtype}")

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

shape of array : (20,)
size of the array : 20
data type of the array : int64


In [44]:
temperature_readings = np.linspace(20,35,8)
print(temperature_readings)
#properties
print(f"shape of array : {temperature_readings.shape}")
print(f"size of the array : {temperature_readings.size}")
print(f"data type of the array : {temperature_readings.dtype}")

[20.         22.14285714 24.28571429 26.42857143 28.57142857 30.71428571
 32.85714286 35.        ]
shape of array : (8,)
size of the array : 8
data type of the array : float64


In [45]:
#tasks 5 image pixel data

In [67]:
grayscale_img = np.full((4,4),128)
print(grayscale_img)
#properties
print(f"shape of array : {grayscale_img.shape}")
print(f"size of the array : {grayscale_img.size}")
print(f"data type of the array : {grayscale_img.dtype}")


[[128 128 128 128]
 [128 128 128 128]
 [128 128 128 128]
 [128 128 128 128]]
shape of array : (4, 4)
size of the array : 16
data type of the array : int64


In [73]:
grayscale_img = grayscale_img.astype(np.uint8)
print(f"data type of the array : {grayscale_img.dtype}")

data type of the array : uint8


In [74]:
reshaped = grayscale_img.flatten()
reshaped.shape

(16,)

In [75]:
reshaped = reshaped.reshape(4,4)
reshaped

array([[128, 128, 128, 128],
       [128, 128, 128, 128],
       [128, 128, 128, 128],
       [128, 128, 128, 128]], dtype=uint8)