In [1]:
import numpy as np

In [2]:
marks = np.array([
    [78, 85, 92],
    [65, 70, 60],
    [90, 88, 95],
    [45, 55, 50],
    [82, 79, 85]
])
marks

array([[78, 85, 92],
       [65, 70, 60],
       [90, 88, 95],
       [45, 55, 50],
       [82, 79, 85]])

In [8]:
print(f"students : {marks.shape[0]}")
print(f"subjects : {marks.shape[1]}")
print(f"total marks stored : {marks.size}")
print(f"dimensions : {marks.ndim}")

students : 5
subjects : 3
total marks stored : 15
dimensions : 2


In [9]:
marks.dtype

dtype('int64')

In [12]:
marks = marks.astype("float64")

In [16]:
new_marks = np.zeros((4,3))
new_marks

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
attendence_sheet = np.ones((5,7))
attendence_sheet

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
schlorship = np.full( (5,1) , 5000 )
schlorship

array([[5000],
       [5000],
       [5000],
       [5000],
       [5000]])

In [27]:
np.arange(1001,1006)

array([1001, 1002, 1003, 1004, 1005])

In [28]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [30]:
print(f"student 2 marks : {marks[1]}")
print(f"student 5 marks : {marks[-1]}")

student 2 marks : [65. 70. 60.]
student 5 marks : [82. 79. 85.]


In [32]:
print(f"students math marks : {marks[0: , 0]}")

students math marks : [78. 65. 90. 45. 82.]


In [33]:
print(f"students english marks : {marks[0: , 2]}")

students english marks : [92. 60. 95. 50. 85.]


In [34]:
print(f"english marks of student 2 to 4 : {marks[1:4,2]}")

english marks of student 2 to 4 : [60. 95. 50.]


In [35]:
print(f"science marks : {marks[0: , 1]}")

science marks : [85. 70. 88. 55. 79.]


In [38]:
marks[3,2] = 58
marks

array([[78., 85., 92.],
       [65., 70., 60.],
       [90., 88., 95.],
       [45., 55., 58.],
       [82., 79., 85.]])

In [43]:
math_marks = marks[0: ,0]
math_marks
mask = math_marks > 80
mask
print(f"students who got greater than 80 in math : {marks[mask]}")

students who got greater than 80 in math : [[90. 88. 95.]
 [82. 79. 85.]]


In [48]:
eng_marks = marks[0:,2]
eng_marks
eng_mask = eng_marks<70
eng_mask
print(f"students who got below 70 in english : {marks[eng_mask]}")

students who got below 70 in english : [[65. 70. 60.]
 [45. 55. 58.]]


In [51]:
students = [0,2,4]
print(f"university wants students 1,3,5 : {marks[students]}")

university wants students 1,3,5 : [[78. 85. 92.]
 [90. 88. 95.]
 [82. 79. 85.]]


In [52]:
print(f"total marks of students : {np.sum(marks,axis=1)}")

total marks of students : [255. 195. 273. 158. 246.]


In [53]:
total_marks = np.sum(marks,axis=0)
print(f"total math marks : {total_marks[0]}")
print(f"total science marks : {total_marks[0]}")
print(f"total english marks : {total_marks[0]}")

total math marks : 360.0
total science marks : 360.0
total english marks : 360.0


In [54]:
print(f"data type of marks : {marks.dtype}")
marks = marks.astype("int64")

data type of marks : float64
