In [11]:
import numpy as np

#task 1 attendence percentages of 10 days


In [7]:
attendence_percentages = np.array([78, 82, 90, 65, 70, 88, 95, 60, 73, 85])
#print the first and last percentages

print(attendence_percentages[0])
print(attendence_percentages[-1])

78
85


In [8]:
#slice out the days from 3 to 7
print(attendence_percentages[2:7])

[90 65 70 88 95]


In [9]:
#Print attendance on every alternate day using step slicing
print(attendence_percentages[::2])

[78 90 70 95 73]


In [10]:
#Reverse the entire array
print(attendence_percentages[::-1])

[85 73 60 95 88 70 65 90 82 78]


In [20]:
#task 2 view trap
sales = np.array([200, 250, 300, 150, 400])
sales

array([200, 250, 300, 150, 400])

In [19]:
subset = sales[0:3]
print(subset)
subset[0] = 0
print(subset)
print(sales)
#in numoy slicing does not give a new array , it gives a view from the orginal array 

[  0 250 300]
[  0 250 300]
[  0 250 300 150 400]


In [21]:
subset = sales[0:3].copy()
subset

array([200, 250, 300])

In [22]:
subset[0]=0
print(subset)
print(sales)

[  0 250 300]
[200 250 300 150 400]


In [24]:
#task 3 
orders = np.array([450, 1200, 300, 5000, 800, 150, 2200, 90])
orders

array([ 450, 1200,  300, 5000,  800,  150, 2200,   90])

In [29]:
#Use boolean masking to get all orders above ₹1000
mask = orders > 1000
print(f"orders greater than 1000 : {mask}")
highest_value=orders[mask]
print(f"high value orders : {highest_value}")

orders greater than 1000 : [False  True False  True False False  True False]
high value orders : [1200 5000 2200]


In [30]:
#Use fancy indexing to fetch orders at positions [1, 3, 6] directly.
idx = [1,3,6]
new_orders = orders[idx]
print(new_orders)

[1200 5000 2200]


In [31]:
#Replace all orders below ₹200 with 0
orders[orders<200] = 0
print(f"orders after zeroing the below 200 to 0 : {orders}")

orders after zeroing the below 200 to 0 : [ 450 1200  300 5000  800    0 2200    0]


In [32]:
#task 4 Classroom marks matrix

In [34]:
student_marks = np.array([[85, 90, 78], [70, 88, 95], [60, 82, 75], [91, 68, 73]])
student_marks

array([[85, 90, 78],
       [70, 88, 95],
       [60, 82, 75],
       [91, 68, 73]])

In [35]:
#Get the marks of the 2nd student (all subjects) using row indexing.
print(student_marks[1])

[70 88 95]


In [42]:
#Get everyone's Science marks (column 1) using column slicing.
print(student_marks[: , 1])


[90 88 82 68]


In [43]:
# Find the total marks per student using axis=1
print(f"total marks per student : { np.sum(student_marks,axis=1) }")

total marks per student : [253 253 217 232]


In [44]:
#Find the average marks per subject using axis=0 with np.mean
print(f"average marks per subject : { np.mean(student_marks , axis=0) }")

average marks per subject : [76.5  82.   80.25]


In [46]:
#Set everyone's English marks (column 2) to 0 
student_marks[ : , 2] = 0
student_marks

array([[85, 90,  0],
       [70, 88,  0],
       [60, 82,  0],
       [91, 68,  0]])

In [47]:
#task 5

In [57]:
image = np.array([
    [50, 200, 30, 180],
    [220, 10, 90, 240],
    [60, 130, 250, 20],
    [170, 80, 5, 210]
])
image

array([[ 50, 200,  30, 180],
       [220,  10,  90, 240],
       [ 60, 130, 250,  20],
       [170,  80,   5, 210]])

In [58]:
print("Shape:", image.shape)  # (4, 4)
image = image.astype(np.uint8)
print("Dtype:", image.dtype) 


Shape: (4, 4)
Dtype: uint8


In [59]:
image[:2 , :2]

array([[ 50, 200],
       [220,  10]], dtype=uint8)

In [60]:
flatten = image.flatten()
flatten

array([ 50, 200,  30, 180, 220,  10,  90, 240,  60, 130, 250,  20, 170,
        80,   5, 210], dtype=uint8)

In [61]:
reshaped = flatten.reshape(4,4)
reshaped

array([[ 50, 200,  30, 180],
       [220,  10,  90, 240],
       [ 60, 130, 250,  20],
       [170,  80,   5, 210]], dtype=uint8)