In [1]:
import numpy as np

In [5]:
sales = np.arange(1,25).reshape(2,3,4)

In [16]:
print(sales)
print(f"shape : {sales.shape}")
print(f"dimensions : {sales.ndim}")
print(f"size : {sales.size}")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape : (2, 3, 4)
dimensions : 3
size : 24


In [19]:
color = np.random.randint(1,256,(3,3,3))

In [27]:
color

array([[[191,  27, 222],
        [139, 212,  25],
        [195,  45, 165]],

       [[196, 219, 127],
        [128,  66,  69],
        [ 97, 205, 178]],

       [[237, 238,  88],
        [129, 140,  22],
        [ 93, 181,  63]]])

In [32]:
color[:3, :3,:2]

array([[[191,  27],
        [139, 212],
        [195,  45]],

       [[196, 219],
        [128,  66],
        [ 97, 205]],

       [[237, 238],
        [129, 140],
        [ 93, 181]]])

In [34]:
student_marks = np.random.randint(40,100,(2,3,4))
student_marks

array([[[53, 62, 77, 55],
        [93, 78, 74, 67],
        [60, 67, 66, 91]],

       [[49, 68, 44, 65],
        [79, 84, 81, 84],
        [51, 62, 49, 51]]])

In [47]:
np.sum(student_marks , axis=2)

array([[247, 312, 284],
       [226, 328, 213]])